import Head from "next/head";
import Menubar from "../../components/Menubar";
export default function Home() {
  return (
    <>
      <Head>
        <title>甘味族 - ギャラリー -</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menubar />
      <MainVisual />
    </>
  );
}

const MainVisual = () => {
  return (
    <section id="main-visual">
      <div className="logo">
        <img src="./images/logo.png" alt="" />
      </div>
    </section>
  );
};
