import Head from "next/head";
import Menubar from "../../components/Menubar";
import Footer from "../../components/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>甘味族 - 商品一覧 -</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menubar />
      <MainVisual />
      <Items />
      <Footer />
    </>
  );
}

const MainVisual = () => {
  return (
    <section id="items-main-visual">
      <div className="inner-container">
        <img src="./images/itemlist-main-img.png" alt="" />
        <div className="logo">
          <img src="./images/logo.png" alt="" />
        </div>
      </div>
    </section>
  );
};

const Items = () => {
  return (
    <section id="items">
      <div className="title">
        <h1>商品一覧</h1>
      </div>

      <p className="description wrapper">
        例年販売している和菓子メニューでございます。
        こちらのメニュー以外にも期間限定のメニューもございます。
        詳細は店舗までお問い合わせ下さい。
      </p>

      <div className="items-gallery">
        <div className="card">
          <div className="img">
            <img src="./images/karukan.png" alt="" />
          </div>
          <p>かるかん</p>
          <p>100円(税込)</p>
        </div>
        <div className="card">
          <div className="img">
            <img src="./images/monaka.png" alt="" />
          </div>
          <p>もなか</p>
          <p>100円(税込)</p>
        </div>
        <div className="card">
          <div className="img">
            <img src="./images/kasutera.png" alt="" />
          </div>
          <p>カステラ</p>
          <p>100円(税込)</p>
        </div>
        <div className="card">
          <div className="img">
            <img src="./images/kasutera-dorayaki.png" alt="" />
          </div>
          <p>カステラどらやき</p>
          <p>100円(税込)</p>
        </div>
        <div className="card">
          <div className="img">
            <img src="./images/usagimoti.png" alt="" />
          </div>
          <p>うさぎもち</p>
          <p>100円(税込)</p>
        </div>
        <div className="card">
          <div className="img">
            <img src="./images/moti.png" alt="" />
          </div>
          <p>もち</p>
          <p>100円(税込)</p>
        </div>
        <div className="card">
          <div className="img">
            <img src="./images/kuri-youkan.png" alt="" />
          </div>
          <p>くりようかん</p>
          <p>100円(税込)</p>
        </div>
        <div className="card">
          <div className="img">
            <img src="./images/kuri-dorayaki.png" alt="" />
          </div>
          <p>くりどらやき</p>
          <p>100円(税込)</p>
        </div>
      </div>
    </section>
  );
};
