import Head from "next/head";
import Menubar from "../../components/Menubar";
export default function Home() {
  return (
    <>
      <Head>
        <title>甘味族 - 商品一覧 -</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Shippori+Mincho&family=Yomogi&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Menubar />
      <MainVisual />
      <Items />
    </>
  );
}

const MainVisual = () => {
  return (
    <section id="items-main-visual">
      <div className="inner-container">
        <img src="./images/itemlist-main-img.png" alt="" />
        <div className="logo">
          <img src="./images/logo.png" alt="" />
        </div>
      </div>
    </section>
  );
};

const Items = () => {
  return (
    <section id="items">
      <div className="title">
        <h1>商品一覧</h1>
      </div>

      <p className="description wrapper">
        例年販売している和菓子メニューでございます。
        こちらのメニュー以外にも期間限定のメニューもございます。
        詳細は店舗までお問い合わせ下さい。
      </p>

      <div className="items-gallery"></div>
    </section>
  );
};
