import Head from "next/head";
import Link from "next/link";
import Menubar from "../components/Menubar";
import SeparatorMaterial from "../components/SeparatorMaterial";
import Footer from "../components/Footer";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const sectionList = document.querySelectorAll("section");

    const callback = (entries, observer) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("view");
        } else {
          entry.target.classList.remove("view");
        }
      });
    };
    const ioOptions = {
      root: null,
      rootMargin: "0px 0px -30% 0px",
    };

    const io = new IntersectionObserver(callback, ioOptions);

    sectionList.forEach((valu, i) => {
      io.observe(valu);
    });
  }, []);

  return (
    <>
      <Head>
        <title>甘味族</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menubar />
      <MainVisual />
      <About />
      <SeparatorMaterial />
      <Craftsman />
      <SeparatorMaterial />
      <CuteJapaneseSweets />
      <SeparatorMaterial />
      <KuriYoukan />
      <SeparatorMaterial />
      <Souvenir />
      <SeparatorMaterial />
      <EatIn />
      <SeparatorMaterial />
      <Footer />
    </>
  );
}

const MainVisual = () => {
  return (
    <section id="main-visual">
      <Link href="./">
        <div className="logo">
          <img src="./images/logo.png" alt="" />
        </div>
      </Link>

      <div className="main-visual-inner">
        <h2>1965年創業</h2>
        <div className="img-monaka">
          <img src="./images/monaka.png" alt="" />
        </div>
        <h2>時代と共に</h2>
      </div>
    </section>
  );
};

const About = () => {
  return (
    <section id="about">
      <div className="title">
        <h1>甘味族とは</h1>
      </div>

      <div className="wrapper">
        <p className="description ">
          甘味族は代々続く和菓子作りの老舗でございます。
          <br />
          日本ならではの細工の細やかさ、季節を感じる彩りを与える一品を添えて。
          <br />
          お客様の日常にささやかな喜びを添え、心に通じる願いを込めて作っております。
        </p>
      </div>

      <div className="img">
        <img src="./images/karukan.png" alt="" />
      </div>
    </section>
  );
};

const Craftsman = () => {
  return (
    <section id="crafts-man" className="base-design-2colum ">
      <div className="title">
        <h1>職人の手で一つ一つ</h1>
      </div>

      <div className="inner-container wrapper">
        <p className="left-content">
          伝統の技法を、ベテランの職人が日々創意工夫しながら、
          「甘味族の味」として継承しています。厳選された素材と、
          職人による技が一つになって美味しさを引き立てます。
        </p>
        <div className="right-content">
          <img src="./images/moti.png" alt="" />
        </div>
      </div>
    </section>
  );
};

const CuteJapaneseSweets = () => {
  return (
    <section id="cute-japanese-sweets">
      <div className="title">
        <h1>かわいい和菓子</h1>
      </div>

      <div className="cute-japanese-sweets-innner wrapper">
        <div className="left-content">
          <img src="./images/sakura-manju.png" alt="" />
        </div>

        <p className="right-content">
          一目見て楽しみ、食べて美味しいのが和菓子です。
          その美観を損なわないよう、外観の隅々まで注意を払い美しく仕上げます。
        </p>
      </div>
      <div className="cute-japanese-sweets-innner wrapper mt-4rem">
        <div className="left-content">
          <img src="./images/kaki-manju.png" alt="" />
        </div>

        <p className="right-content">
          日々変化していくニーズも取り入れ、甘味族の良さと両立できるよう心がけています。
        </p>
      </div>
    </section>
  );
};

const KuriYoukan = () => {
  return (
    <section id="kuri-youkan" className="base-design-2colum">
      <div className="title">
        <h1>当店の看板メニュー</h1>
      </div>

      <div className="inner-container wrapper">
        <p className="left-content">
          こしあんと栗のペーストを使ってなめらかな口当たりに仕上げました。
          栗をたっぷり入れて贅沢さを是非ご堪能下さい。
        </p>
        <div className="right-content">
          <img src="./images/kuri-youkan.png" alt="" />
        </div>
      </div>
    </section>
  );
};

const Souvenir = () => {
  return (
    <section id="souvenir">
      <div className="title">
        <h1>お土産にもピッタリ</h1>
      </div>

      <p className="description wrapper">
        甘味族はあんこを使った和菓子が主流ですが、
        他にも様々な和菓子をお造りしております。
        お土産にもピッタリな和菓子や、日常でお召し上がり頂ける和菓子まで
        ございますので、ぜひご覧ください。
      </p>

      <div className="img-grid wrapper">
        <div className="img">
          <img src="./images/kuri-dorayaki.png" alt="" />
        </div>
        <div className="img">
          <img src="./images/kasutera-dorayaki.png" alt="" />
        </div>
        <div className="img">
          <img src="./images/usagimoti.png" alt="" />
        </div>
        <div className="img">
          <img src="./images/kasutera.png" alt="" />
        </div>
      </div>

      <p className="description wrapper">
        他にも様々なメニューをご用意しております。
        <br />
        詳しくは商品一覧ページとギャラリーページをご覧ください。
      </p>

      <div className="inner-container">
        <div className="link-btn">
          <Link href="./items">商品一覧はこちら</Link>
        </div>
        <div className="link-btn">
          <Link href="./gallery">ギャラリーはこちら</Link>
        </div>
      </div>
    </section>
  );
};

const EatIn = () => {
  return (
    <section id="eat-in" className="base-design-2colum">
      <div className="title">
        <h1>店内でもお召し上がりいただけます</h1>
      </div>

      <div className="inner-container wrapper">
        <p className="left-content">
          当店はお持ち帰り以外にも、イートインスペースを設けております。
          是非ご利用くださいませ。
        </p>
        <div className="right-content">
          <img src="./images/shop.png" alt="" />
        </div>
      </div>
    </section>
  );
};
