import Head from "next/head";
import Menubar from "../components/Menubar";

export default function Home() {
  return (
    <>
      <Head>
        <title>甘味族</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Shippori+Mincho&family=Yomogi&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Menubar />
    </>
  );
}
